### ISSUE TITLE
Crashing on PaperMC 

### ISSUE THREAD

**Issue by vextechs** [PvPHubLLC/Blossom#2]
@xyzaurora 
[Log.log](https://github.com/PvPHubLLC/Blossom/files/11413399/Log.log)
Here is the log of the server. It seems to crash on startup and pfclown is still able to connect. I am using release 1.1.

**Comment by RandomHuman2020** [comment]
can confirm on my server, same error

**Comment by xyzaurora** [comment]
Could you try 1.1?

**Comment by xyzaurora** [comment]
This is #1 I just fixed that.

**Comment by vextechs** [comment]
I download the blossom-backend-dev-all.jar from version 1.1 release.

**Comment by xyzaurora** [comment]
Seems like the jar I uploaded wasnt updated, sorry for all the trouble, making 1.2 now.

**Comment by xyzaurora** [comment]
Done
