### ISSUE TITLE
More transparency

### ISSUE THREAD

**Issue by D-VR** [PvPHubLLC/Blossom#5]
You may want to highlight how the Blacklist works.

i.e. that it sends every IP to your API to be checked.

It might also be good to state how you use that data, or if you don't store it at all

**Comment by xyzaurora** [comment]
We have a 0 log policy, nothing gets logged from the clients.

**Comment by D-VR** [comment]
thank you for the answer! It would be good if this gets added to the FAQ or stated somewhere else :)
