### ISSUE TITLE
Feature request: Local control

### ISSUE THREAD

**Issue by SlimeDog** [PvPHubLLC/Blossom#6]
How about a version that does not require a network connection or external database. Let us configure the IP addresses that we have detected, then `blossom reload` to pick up the IP addresses that should be blocked. Use notation similar to that required by a firewall. For example, based on the current scanners we have detected locally:

config.yml
```
blacklist:
- 45.128.232.206/32
- 193.35.18.0/24
```

**Comment by Matt-MX** [comment]
What's the need for a local point? Any ideas as to how and why that'd be added?

**Comment by SlimeDog** [comment]
Blossom is a good idea, but ...

At present, I block detected scanner IP addresses at my firewall. It would be convenient to use Blossom to do so, but there is no need to query a networked database to identify the malignant IP addresses -- I can identify the (currently 3) culprits.

**Comment by SlimeDog** [comment]
Please confirm if there is an intention to do this, or not.

**Comment by SlimeDog** [comment]
After the passage of time, I'm guessing not.
